
resource "local_file" "PetOne" {
    filename = var.filename
    content = "My favorite pet is a ${random_pet.PetTwo.id}"
    }

resource "random_pet" "PetTwo"{
    prefix = var.prefix
    separator = var.separator
    length = var.length
}

output "pet-name" {
    value = random_pet.PetTwo
    description = "Record of the value of pet ID generated by the random_pet resource"
  }